version: "3.9"

services:
  backend:
    build: .
    volumes:
      - ".:/code"
    depends_on:
      - cache
    networks:
      - monitoring

  cache:
    image: redis:6.2.6-alpine3.15
    volumes:
      - "/opt/redis-data:/var/lib/redis"
    ports:
      - "6379"
    command: redis-server --requirepass supersecret
    networks:
      - monitoring

  nginx:
    image: nginx:1.21.5-alpine
    volumes:
      - "./site.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
    networks:
      - monitoring

networks:
 monitoring:
    driver: bridge
    name: monitoring

