version: "3.9"

services:
  backend:
    build: .
    volumes:
      - ".:/code"
    depends_on:
      - cache
    ports:
      - "8081:8081"
    networks:
      - monitoring

  cache:
    image: redis:6.2.6-alpine3.15
    volumes:
      - "/opt/redis-data:/var/lib/redis"
    ports:
      - "6379"
    command: redis-server --requirepass supersecret
    networks:
      - monitoring

networks:
 monitoring:
    driver: bridge
    name: monitoring
